### ISSUE TITLE
Check and correct all instances of placement new

### ISSUE THREAD

**Issue by joewpeterson** [njoy/scion#79]
Placement new was implemented ( particularly within class's operator= ) in a way which will create memory leaks under certain circumstances. 

Calling: new (this) MyClass( base ); 

will construct a whole new instance of MyClass with the constructor input of base. It will place that newly created instance at address of (this). This is done without knowing or caring what (this) references. The call trusts the programmer has allocated enough space at (this) and does not need the data previously held at (this) - the data is overwritten by the instance created by the MyClass constructor. 

When the placement operator is called within the context of (this) referencing a class with heap allocation, the reference to (this)'s heap allocation is lost, creating a memory leak

**Comment by whaeck** [comment]
I think this has been resolved now.
